console.log(Seu_nome = "Thiago Pereira Gonçalves")
console.log(Seu_email = "thiago19.pgoncalves@gmail.com")
console.log(Sua_profissão = "Eletricista")
console.log(Sua_idade = 36)
console.log(lugar_para_conhecer = "Portugal")
